apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-hub
  template:
    metadata:
      labels:
        app: anime-hub
    spec:
      containers:
      - name: anime-hub-webapp
        image: akshaypatil7485/anime-hub-webapp:latest
        ports:
        - containerPort: 8080  # Change the port to 8080 apache listes port 8080
        readinessProbe:
            httpGet:
              path: /server-status
              port: 8080
        livenessProbe:
            httpGet:
              path: /server-status
              port: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: anime-hub-service
spec:
  selector:
    app: anime-hub
  ports:
    - protocol: TCP
      port: 8080   # Port exposed inside the Kubernetes cluster
      targetPort: 8080  # Port in the container to route traffic to
      nodePort: 30080   # <-- Expose this port externally via NodePort (can be any available port in the range 30000-32767)
  type: NodePort  # Use NodePort to expose the service on a node port
