apiVersion: apps/v1
kind: Deployment
metadata:
  name: coza-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coza-store
  template:
    metadata:
      labels:
        app: coza-store
    spec:
      containers:
      - name: coza-store-webapp
        image: akshaypatil7485/coza-store-webapp:latest
        ports:
        - containerPort: 8080  # Change the port to 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coza-store-service
spec:
  selector:
    app: coza-store
  ports:
    - protocol: TCP
      port: 8080   # Port exposed inside the Kubernetes cluster
      targetPort: 8080  # Port in the container to route traffic to
      nodePort: 30080   # <-- Expose this port externally via NodePort (can be any available port in the range 30000-32767)
  type: NodePort  # Use NodePort to expose the service on a node port
